### PR TITLE
Fix 2 'divide by zero' issues. This should fix https://github.com/tek…

### LINKED ISSUE #2: divide-by-zero in main (aacplusenc.c)
On 0.17.5:

```
# aacplusenc $FILE out.aac 32
                                                                                                                                                                                                                  
*************************************************************                                                                                                                                                     
* Enhanced aacPlus Encoder                                                                                                                                                                                        
* Build Aug 30 2017, 14:40:49                                                                                                                                                                                     
* Matteo Croce <rootkit85@yahoo.it>                                                                                                                                                                               
*************************************************************                                                                                                                                                     
                                                                                                                                                                                                                  
input file 1.crashes.wav:                                                                                                                                                                                         
sr = 48000, nc = 1                                                                                                                                                                                                
                                                                                                                                                                                                                  
output file out.aac:                                                                                                                                                                                              
br = 32000 sr-OUT = 48000  nc-OUT = 1                                                                                                                                                                             

ASAN:DEADLYSIGNAL
=================================================================
==17545==ERROR: AddressSanitizer: FPE on unknown address 0x00000050a920 (pc 0x00000050a920 bp 0x7ffea4ed2840 sp 0x7ffea4ed26a0 T0)
    #0 0x50a91f in main /var/tmp/portage/media-sound/aacplusenc-0.17.5/work/aacplusenc/aacplusenc.c:522:64
    #1 0x7f82eec2b680 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.23-r4/work/glibc-2.23/csu/../csu/libc-start.c:289
    #2 0x419e78 in _init (/usr/bin/aacplusenc+0x419e78)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /var/tmp/portage/media-sound/aacplusenc-0.17.5/work/aacplusenc/aacplusenc.c:522:64 in main
==17545==ABORTING
```

Testcase attached:
[testcase.zip](https://github.com/teknoraver/aacplusenc/files/1266160/testcase.zip)

### PR DESCRIPTION
**Pull request by Oele**
This should fix #2 and another similar case.

### CODE REVIEW

**Comment by Oele** [comment]
It also seems to fix #1 .

**Comment by teknoraver** [comment]
good.
maybe indent it properly (tabs, 8 spaces per tab) so it looks good in github

**Comment by Oele** [comment]
Better?

**Comment by teknoraver** [comment]
Yes, but I'll squash them

**Pull request merged**
