### PR TITLE
Move the -l options to the end of the gcc command to allow building with recent gcc

### PR DESCRIPTION
**Pull request by Oele**

### CODE REVIEW

**Comment by teknoraver** [comment]
Can you refactor the patch using `LIBS` instead of `LDFLAGS`?

**Comment by Oele** [comment]
Something like this?

**Comment by teknoraver** [comment]
Yes, sort of.

I'm reading the [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) and it seems that `-L` arguments should go into `LDFLAGS` while `-l` into `LDLIBS`

Does it work for you?

**Comment by Oele** [comment]
Yes I had to look that up too ;) But I think that what we have now is consistent with the manual, right? 

```
LDFLAGS=-L$(TOPDIR)/libaacenc -L$(TOPDIR)/libbitbuf -L$(TOPDIR)/libfr -L$(TOPDIR)/libsbrenc -L$(TOPDIR)/libresamp
LDLIBS=-laacenc -lbitbuf -lfr -lsbrenc -lresamp -lm
```

All fine with me of course!

**Comment by Oele** [comment]
Oh and yes, it works.

**Comment by teknoraver** [comment]
yes, that's correct

**Pull request merged**
